version: '3.9'

services:
  study-bot:
    container_name: study-bot
    build:
      context: .
      dockerfile: ./build/study/Dockerfile
    restart: always
    environment:
      CONFIG_FILE: config.json
      TIME_ZONE: Asia/Seoul
    configs:
      - source: bot-config
        target: /app/config.json
    depends_on:
      - redis
      - rabbitmq

  study-logger:
    container_name: study-logger
    build:
      context: .
      dockerfile: ./build/logger/Dockerfile
    restart: always
    environment:
      LOGGER_CONFIG_FILE: config.json
      SHEETS_CREDENTIALS: creds.json
      SPREADSHEET_ID: 1a4VByiDovdJjEcLRsZjCNMAWab-stdKdsN23JVKA7rk
      TIME_ZONE: Asia/Seoul
    configs:
      - source: logger-config
        target: /app/config.json
      - source: sheets-creds
        target: /app/creds.json
    depends_on:
      - rabbitmq

  redis:
    container_name: redis
    image: redis:7.0.11-alpine
    command: redis-server /usr/local/etc/redis/redis.conf
    labels:
      - "name=redis"
      - "mode=standalone"
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./configs/reids/redis.conf:/usr/local/etc/redis/redis.conf

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.11.16-management
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
      - 9419:9419

  rabbitmq-exporter:
    container_name: rabbitmq-exporter
    image: kbudde/rabbitmq-exporter:latest
    restart: always
    network_mode: service:rabbitmq


  prometheus:
    container_name: prometheus
    image: 'prom/prometheus:v2.44.0'
    restart: always
    ports:
      - 9090:9090
    volumes:
      - prometheus-data:/prometheus
      - ./configs/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    container_name: grafana
    image: 'grafana/grafana:9.5.2'
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - 3000:3000
    restart: always
    volumes:
      - grafana-data:/var/lib/grafana
      - ./configs/grafana/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
    depends_on:
      - prometheus

volumes:
  prometheus-data:
    driver: local
  grafana-data:
    driver: local

configs:
  bot-config:
    file: ./configs/config-study-dev.json
  logger-config:
    file: ./configs/config-logger-dev.json
  sheets-creds:
    file: ./configs/config-sheets-dev.json