version: '3.9'

services:
  study-bot:
    container_name: study-bot
    image: piatoss3612/study-bot:latest
    restart: always
    environment:
      CONFIG_FILE: config.json
      TIME_ZONE: Asia/Seoul
    configs:
      - source: bot-config
        target: /app/config.json
    depends_on:
      - redis
      - rabbitmq

  study-logger:
    container_name: study-logger
    image: piatoss3612/study-logger:latest
    restart: always
    environment:
      LOGGER_CONFIG_FILE: config.json
      SHEETS_CREDENTIALS: creds.json
      SPREADSHEET_ID: 1a4VByiDovdJjEcLRsZjCNMAWab-stdKdsN23JVKA7rk
      EVENT_SHEET_ID: 1024
      TIME_ZONE: Asia/Seoul
    configs:
      - source: recorder-config
        target: /app/config.json
      - source: sheets-creds
        target: /app/creds.json
    depends_on:
      - rabbitmq

  redis:
    container_name: redis
    image: redis:7.0.11-alpine
    command: redis-server /usr/local/etc/redis/redis.conf
    labels:
      - "name=redis"
      - "mode=standalone"
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./configs/redis.conf:/usr/local/etc/redis/redis.conf

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.11.16-management
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    

configs:
  bot-config:
    file: ./configs/config-dev.json
  recorder-config:
    file: ./configs/config-recorder-dev.json
  sheets-creds:
    file: ./configs/config-sheets-dev.json