---
global:
  scrape_interval: 5s
  evaluation_interval: 5s

alerting:

rule_files:

scrape_configs:
  - job_name: rabbitmq
    metrics_path: "/metrics"
    static_configs:
      - targets: ["rabbitmq:9419"]
  - job_name: study-bot
    metrics_path: "/metrics"
    static_configs:
      - targets: ["study-bot:8080"]
